#!/usr/bin/env python3
"""Inject pack/envoy prefixes + optional HA token into runtime config.js."""

from __future__ import annotations

import json
import os
import re
from pathlib import Path

OPTIONS = Path(os.environ.get("SI_OPTIONS", "/data/options.json"))
TEMPLATE = Path(
    os.environ.get("SI_CONFIG_TEMPLATE", "/opt/sunny_island_detail/www/js/config.js")
)
OUT = Path(os.environ.get("SI_CONFIG_OUT", "/data/config.js"))


def main() -> int:
    opts = {}
    if OPTIONS.exists():
        opts = json.loads(OPTIONS.read_text())

    pack = str(opts.get("pack_prefix") or "battery_storage_tesla_pack").strip()
    envoy = str(
        opts.get("envoy_prefix") or "sensor.envoy_122039004946"
    ).strip()
    token = str(opts.get("ha_token") or "").strip()

    body = TEMPLATE.read_text()
    body = re.sub(
        r"const PACK_PREFIX = ['\"].*?['\"];",
        lambda _m: f"const PACK_PREFIX = {json.dumps(pack)};",
        body,
        count=1,
    )
    body = re.sub(
        r"const ENVOY_PREFIX = ['\"].*?['\"];",
        lambda _m: f"const ENVOY_PREFIX = {json.dumps(envoy)};",
        body,
        count=1,
    )

    boot = ""
    if token:
        boot = f"""
try {{
  if (!localStorage.getItem('sunny_island_detail_ha_token')) {{
    localStorage.setItem('sunny_island_detail_ha_token', {json.dumps(token)});
  }}
}} catch (e) {{}}
"""

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(
        "/** Runtime config — generated by HAOS add-on */\n" + body + boot
    )
    print(f"[sunny_island_detail] pack={pack} envoy={envoy}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
